services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/webring
      - SECRET_KEY=${SECRET}
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:17.2
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webring

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_SERVER=${API_SERVER}
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
