services:
  backend:
    build: ./backend
    # ports:
    #   - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/webring
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:17.2
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webring
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./frontend
      args:
        # idk why this does not work, set in Dockerfile if this does not work
        - NEXT_PUBLIC_API_SERVER=http://localhost:3000
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
